Question 17 | Audit Log Policy

1. Change the Configuration so that only one backup of the logs is stored.
2. Alter the Policy in a way that it only stores logs:
  - from secret resources, level Metadata
  - from syste:nodes userGroup, level RequestResponse

  After you update the Policy make sure to empty the log file so it only contains entries accoding to yout changes
like using echo > /etc/kubernetes/audot/logs/audit.log

cp /etc/kubernetes/manifest/kube-apiserver.yaml ~/17_kube-apiserver.yaml # backup

vim /etc/kubernetes/manifests/kube-apiserver.yaml 



- --audit-log-maxbackup=1



vim /etc/kubernets/audot/policy.yaml
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
  resources:
  - group: ""
    resources: ["secrets"]

- level: RequestResponse
  userGroups: ["system:nodes"]

- level: None

